#
# Analyze repository with PSRule
#

# Note:
# This workflow is designed to run only in Azure/PSRule.Rules.Azure-governed.
# You can safely deleted this file if you have templated this repository to your GitHub organization.

# For PSRule documentation see:
# https://aka.ms/ps-rule

# For action details see:
# https://aka.ms/ps-rule-action

name: Analyze repository

# Run for main or PRs against main
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    if: github.repository == 'Azure/PSRule.Rules.Azure-governed'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run PSRule analysis
        uses: microsoft/ps-rule@46451b8f5258c41beb5ae69ed7190ccbba84112c # v2.9.0
        with:
          modules: PSRule.Rules.MSFT.OSS
